### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by qwibbler** [melaniesigrid/portfolio#11]
Great job on your code, and good luck in your future endeavours! 👍 👍 
Here are some suggestions our team had that you can implement:

- [x] You are using two constants for one variable, maybe you could combine them into one.
- [x] There is an overflow when you open a modal. You could add an `overflow` property to the css.
- [x] Define your functions before you call them or you will have linter errors.

🤞

**Comment by melaniesigrid** [comment]
Thank you for your review! I have taken care of correcting the issue.
