### ISSUE TITLE
Peer to Peer Code Review

### ISSUE THREAD

**Issue by zhadier** [melaniesigrid/portfolio#15]
### Great job on the code so far
Here are a few suggestions
- try to either keep the a tags or the button, nesting them inside each other can cause linter errors
<img src="https://media4.giphy.com/media/z8XtwKGIRQSBCmU4sW/giphy.gif"/>

**Comment by melaniesigrid** [comment]
Thank you for your review. It was helpful, I have finally taken care of this issue! 😄
